// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKqdbMZ4yj5dOvUYqQygZ-f1Rnu2c-Njk',
    appId: '1:541456022122:web:dcf5778630c3011fc5a813',
    messagingSenderId: '541456022122',
    projectId: 'chat-app-dc48e',
    authDomain: 'chat-app-dc48e.firebaseapp.com',
    storageBucket: 'chat-app-dc48e.appspot.com',
    measurementId: 'G-8VWF1GWEYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOSve87BwPavedPGm3fU1XfJp711V6d5s',
    appId: '1:541456022122:android:a39ec90f4b64e90cc5a813',
    messagingSenderId: '541456022122',
    projectId: 'chat-app-dc48e',
    storageBucket: 'chat-app-dc48e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiA2NxuZsxfAyziivhG6clJgKMxobhZOA',
    appId: '1:541456022122:ios:d863a5f900367bbdc5a813',
    messagingSenderId: '541456022122',
    projectId: 'chat-app-dc48e',
    storageBucket: 'chat-app-dc48e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiA2NxuZsxfAyziivhG6clJgKMxobhZOA',
    appId: '1:541456022122:ios:307337dae85e1c94c5a813',
    messagingSenderId: '541456022122',
    projectId: 'chat-app-dc48e',
    storageBucket: 'chat-app-dc48e.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
